engines:
  radon:
    enabled: true
    config:
       threshold: "C"
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
    checks:
      bug:
        enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "tlsfuzzer/**"
  - "**.py"
exclude_paths:
 - "tests/*"
 - "scripts/*"
